server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: http://localhost:8070/
          predicates:
            - Path=/movies/**
        - id: catalogRoute
          uri: http://localhost:8071/
          predicates:
            - Path=/catalog/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
