server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          searchPaths: config_yml
          uri: https://github.com/Winst0nPy/ctd_microservices_evaluation

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka